### ISSUE TITLE
modules

### ISSUE THREAD

**Issue by rtef23** [rtef23/igor#2]
#### TODO
- [ ] create database scheme
- [ ] improve search
- [ ] synchronize module data - module file
- [ ] front work(react)
- [ ] back work(java-spring)
