### ISSUE TITLE
server-setting

### ISSUE THREAD

**Issue by rtef23** [rtef23/igor#3]
#### TODO
- [ ] configure nginx setting
- [ ] configure ssl setting
- [ ] configure rotate log setting
- [ ] configure tomcat setting
- [ ] configure nginx-tomcat proxy setting

**Comment by rtef23** [comment]
#### 공유기 관리자
접근 경로 [http://192.168.35.1/first.asp](http://192.168.35.1/first.asp)
id : admin

**Comment by rtef23** [comment]
#### NAS
접근 경로 [http://192.168.35.209:5000/](http://192.168.35.209:5000/)
